import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ backendData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>testing Page for Transport</h1>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>check Images &rarr;</h2>
            <Image
              width={500}
              height={500}
              objectFit="contain"
              objectPosition="center"
              alt="truck"
              src="/truck.png"
              loading="eager"
            />
          </a>
        </div>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>check envs &rarr;</h2>
            <p style={{ minWidth: "100%" }}>{process.env.NEXT_PUBLIC_TEXT}</p>
          </a>
        </div>
        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>data from Backend &rarr;</h2>
            <p style={{ minWidth: "100%" }}>{backendData.text}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch(`${process.env.HOST}:${process.env.PORT}/api/hello`);
  const data = await res.json();
  if (!data) {
    return {
      notFound: true,
    };
  }
  return {
    props: { backendData: data },
  };
}
